// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhnrlfobskkebvwbsiiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJobnJsZm9ic2trZWJ2d2JzaWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTYzOTUsImV4cCI6MjA3MzUzMjM5NX0._K7VEO6lJ2kZBCASPD-2wa1sx3RAlpgrefbFWHacF2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});